Repository bratergit/brazilstocks, pull requests merged in 2025-10, with the labels that each got.

#21 ADDED LICENSE
  LICENSE
Labels: documentation, enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#23 feat(data): add get_stock_data via yfinance (#5)
  .gitignore
  examples/__pycache__/fetch_b3.cpython-311.pyc
  examples/fetch_b3.py
  requirement.txt
  src/__init__.py
  src/__pycache__/__init__.cpython-311.pyc
  src/data/__init__.py
  src/data/__pycache__/__init__.cpython-311.pyc
  src/data/__pycache__/b3_data.cpython-311.pyc
  src/data/b3_data.py
  tests/test_b3_data.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, feature

#24 Replace Unlicense with MIT License and update README with license section
  LICENSE
  README.md
Labels: bug, documentation, enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, feature

#27 Docs: Add Local Setup section to README
  README.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#29 fixing some issues
  src/data/fx_scraper.py
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, feature

#32 Added Function To Calculate Compounded Monthly Returns
  app.py
  src/data/__init__.py
  src/data/b3_data.py
  src/utils/__init__.py
  src/utils/investment_calculator.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, feature

#33 Added CI.yml workflow
  .github/workflows/ci.yml
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted
